### PR TITLE
fix: Prevent "Connection closed" errors when deleting the session for @wdio/cucumber-framework

### LINKED ISSUE #115: Unexpected "Connection closed" when runing with @wdio/cucumber-framework
### Problem

When I use @wdio/cucumber-framework to run my tests
Then I see an unexpected `Error: Connection closed. Code: 1006`

```
> wdio run ./test/wdio.conf.ts

Execution of 1 workers started at 2024-02-26T22:11:39.549Z

Skipping download, bundle for ChromeDriver v27.2.3 already exists
Found existing install in .../.wdio-vscode-service/vscode-linux-arm64-1.86.2. Skipping download

[0-0] RUNNING in chrome - file:///test/features/webview.feature
[0-0] file:///.../node_modules/wdio-vscode-service/src/service.ts:60
[0-0]         this._promisedSocket = Promise.reject(new Error(msg))
[0-0]                                               ^
[0-0] Error: Connection closed. Code: 1006, reason: 
[0-0]     at VSCodeWorkerService._handleSocketClose (file:///.../node_modules/wdio-vscode-service/src/service.ts:60:47)
[0-0]     at Object.onceWrapper (node:events:629:26)
[0-0]     at WebSocket.emit (node:events:526:35)
[0-0]     at WebSocket.emit (node:domain:488:12)
[0-0]     at WebSocket.emitClose (.../node_modules/wdio-vscode-service/node_modules/ws/lib/websocket.js:265:10)
[0-0]     at Socket.socketOnClose (.../node_modules/wdio-vscode-service/node_modules/ws/lib/websocket.js:1289:15)
[0-0]     at Socket.emit (node:events:514:28)
[0-0]     at Socket.emit (node:domain:488:12)
[0-0]     at TCP.<anonymous> (node:net:337:12)
[0-0] FAILED in chrome - file:///test/features/webview.feature

Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:08  

```

### Steps to Reproduce

I've reproduced the error from a private repo in https://github.com/seanpoulter/wdio-vscode-cucumber-example:

```
nvm install --lts
nvm use --lts
npm ci
npm run test
```

### Analysis

The error is thrown from line 60 https://github.com/webdriverio-community/wdio-vscode-service/blob/92b7b6b8ba8def19eb446cae7a1f9107150caffb/src/service.ts#L58-L62

which is registered on line 116

https://github.com/webdriverio-community/wdio-vscode-service/blob/92b7b6b8ba8def19eb446cae7a1f9107150caffb/src/service.ts#L110-L117

### Questions

* Since `this._promisedSocket` is assigned in `beforeSession` hook, does it make sense to use the `deleteSession` hook to reset `this._promisedSocket = undefined`?
* If this only affects Cucumber, does the solution belong there?

### PR DESCRIPTION
**Pull request by seanpoulter**
### Proposed Changes

This fixes #115.

### Validation

Since we don't have Cucumber set up in this repo I used [seanpoulter/wdio-vscode-cucumber-example](https://github.com/seanpoulter/wdio-vscode-cucumber-example):

```
$ cd .../wdio-vscode-﻿service
$ npm link
$ npm run build

$ cd .../wdio-vscode-cucumber-example
$ npm link wdio-vscode-service

$ npm run test


> test
> wdio run ./test/wdio.conf.ts


Execution of 1 workers started at 2024-02-27T01:45:04.115Z

Skipping download, bundle for ChromeDriver v27.2.3 already exists
Found existing install in .../.wdio-vscode-service/vscode-linux-arm64-1.86.2. Skipping download
[0-0] RUNNING in chrome - file:///test/features/webview.feature
[0-0] PASSED in chrome - file:///test/features/webview.feature

 "spec" Reporter:
------------------------------------------------------------------
[chrome 118.0.5993.159 linux #0-0] Running: chrome (v118.0.5993.159) on linux
[chrome 118.0.5993.159 linux #0-0] Session ID: 90871adafb5727ca052e30dc884ec9e9
[chrome 118.0.5993.159 linux #0-0]
[chrome 118.0.5993.159 linux #0-0] » /test/features/webview.feature
[chrome 118.0.5993.159 linux #0-0] Hello World
[chrome 118.0.5993.159 linux #0-0] As an extension developer
[chrome 118.0.5993.159 linux #0-0] I want to test if a Webview is displayed
[chrome 118.0.5993.159 linux #0-0]
[chrome 118.0.5993.159 linux #0-0] Webview Shows "Hello World!"
[chrome 118.0.5993.159 linux #0-0]    ✓ When I open the Webview
[chrome 118.0.5993.159 linux #0-0]    ✓ Then I expect that "Hello World!" is displayed
[chrome 118.0.5993.159 linux #0-0]
[chrome 118.0.5993.159 linux #0-0] 2 passing (3.2s)


Spec Files:      1 passed, 1 total (100% completed) in 00:00:10  
```

:tada:

### CODE REVIEW

File: src/service.ts [hunk 1]
```diff
@@ -56,9 +57,11 @@ export default class VSCodeWorkerService implements Services.ServiceInstance {
...
 
     private _handleSocketClose (code: number, reason: Buffer) {
-        const msg = `Connection closed. Code: ${code}, reason: ${reason.toString()}`
-        this._promisedSocket = Promise.reject(new Error(msg))
-        this._pendingMessages.forEach((resolver) => resolver(msg, null))
+        if (!this._deletingSession) {
+            const msg = `Connection closed. Code: ${code}, reason: ${reason.toString()}`
+            this._promisedSocket = Promise.reject(new Error(msg))
+            this._pendingMessages.forEach((resolver) => resolver(msg, null))
+        }
```
Comment (christian-bromann) [inline src/service.ts:64]:
```suggestion
        if (this._deletingSession) {
            return
        }
        const msg = `Connection closed. Code: ${code}, reason: ${reason.toString()}`
        this._promisedSocket = Promise.reject(new Error(msg))
        this._pendingMessages.forEach((resolver) => resolver(msg, null))
```

File: src/service.ts [hunk 2]
```diff
@@ -163,6 +167,12 @@ export default class VSCodeWorkerService implements Services.ServiceInstance {
         log.info(`Start VSCode: ${binary} ${args.join(' ')}`)
     }
 
+    beforeCommand (commandName: string): void {
+        if (commandName === 'deleteSession') {
```
Comment (christian-bromann) [inline src/service.ts:171]: Let's also verify that the session is Cucumber and add a comment documenting why we have this special case for it.

**Review by christian-bromann — COMMENTED** [review]
I am a bit confused as to why Cucumber behaves differently here. Added some comments to make this change a bit more clear to contributors in the future.

**Comment by seanpoulter** [comment]
> I am a bit confused as to why Cucumber behaves differently here.

Me too. There wasn't anything obvious comparing the `run` method for the Mocha and Cucumber frameworks. As a hunch, it seems like Mocha is either not making request after the test case, or it's hiding the rejected promise.

File: src/service.ts (hunk 2 above)
Comment (seanpoulter) [reply src/service.ts:179]: **Done**. It is set in `beforeSession` to have access to `config`.

**Review by christian-bromann — APPROVED** [review]
LGTM :shipit:
